# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"foo": "00_core.ipynb",
         "moo": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://deven367.github.io/foo/"

git_url = "https://github.com/deven367/foo/tree/master/"

def custom_doc_links(name): return None
