# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['foo', 'moo']

# Cell
def foo(
    x: int, # number
    )->int: # same number
    "returns same number"
    return x

# Cell
def moo(
    x: int, # number
    )->int: # same number
    "returns same number"
    return x